# Generated by Django 4.1.6 on 2023-11-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interact_uz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about_item', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default='$', max_length=10)),
                ('price', models.IntegerField()),
                ('type_catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.category')),
            ],
        ),
    ]
