# Generated by Django 4.1.6 on 2023-11-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interact_uz', '0003_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_sites',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='web_sites',
            name='about_item',
            field=models.TextField(max_length=4096),
        ),
        migrations.CreateModel(
            name='telegram_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about_item', models.TextField(max_length=4096)),
                ('image', models.ImageField(upload_to='')),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default='$', max_length=10)),
                ('link', models.URLField(blank=True)),
                ('price', models.IntegerField()),
                ('type_catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.category')),
            ],
        ),
        migrations.CreateModel(
            name='free_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.TextField()),
                ('about_item', models.TextField(max_length=4096)),
                ('image', models.ImageField(upload_to='')),
                ('type_catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.category')),
            ],
        ),
    ]
