# Generated by Django 4.1.6 on 2023-12-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact_uz', '0005_authors_delete_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
