# Generated by Django 4.1.6 on 2023-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact_uz', '0006_delete_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
