# Generated by Django 4.1.6 on 2023-12-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interact_uz', '0010_remove_free_codes_author_remove_free_codes_type_catg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web_sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about_item', models.TextField(max_length=4096)),
                ('image', models.ImageField(upload_to='')),
                ('screen1', models.ImageField(upload_to='')),
                ('screen2', models.ImageField(upload_to='')),
                ('screen3', models.ImageField(upload_to='')),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default='$', max_length=10)),
                ('link', models.URLField(blank=True)),
                ('price', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.authors')),
                ('type_catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.category')),
            ],
        ),
        migrations.CreateModel(
            name='telegram_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('about_item', models.TextField(max_length=4096)),
                ('image', models.ImageField(upload_to='')),
                ('screen1', models.ImageField(upload_to='')),
                ('screen2', models.ImageField(upload_to='')),
                ('screen3', models.ImageField(upload_to='')),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default='$', max_length=10)),
                ('link', models.URLField(blank=True)),
                ('price', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.authors')),
                ('type_catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.category')),
            ],
        ),
        migrations.CreateModel(
            name='free_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.TextField()),
                ('about_item', models.TextField(max_length=4096)),
                ('image', models.ImageField(upload_to='')),
                ('screen1', models.ImageField(upload_to='')),
                ('screen2', models.ImageField(upload_to='')),
                ('screen3', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.authors')),
                ('type_catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interact_uz.category')),
            ],
        ),
    ]
