# Generated by Django 4.1.6 on 2023-12-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact_uz', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_codes',
            name='screen1',
        ),
        migrations.RemoveField(
            model_name='free_codes',
            name='screen2',
        ),
        migrations.RemoveField(
            model_name='free_codes',
            name='screen3',
        ),
    ]
